notifications:
   email: false
    
os:
  - linux

sudo: required

language: java

services:
  - xvfb

jdk:
  - oraclejdk8

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:    
    - build-essential
    - graphviz
    - openssl
    - libssl-dev

env:
  global:
  - secure: FFBOvoAf+V3AsDV+VHSymGi8eoVrjtlaXOsZPKy6FQnvSP9JWfUQz/QDB74HK96t04pMu3SnaOZNCI3K/dkZ3RS/wY8J+TKYTdhcTT+7zPYgn564AV3J7lGl7ozcKWhDUAqC+ti9tpIPGbtKO9iIkXLsaK8ZXd2iT1Qu92deYEnTVdoyiASRb4tMq37ROf2ufvWDauT0x5ozJ3H76m306UMZcUEIa7MlHoiOZz1YHzdQn/K7obVW6wdT8X2NgH7XoepUyC0VI03Xymo+eY5AHth8K5hstJU2dhIYNv9RJwkDgW/5kW9jFqrKl/o5bZjNE9kkeRADRuBbnq0lNhLSGMF4wc2y6vx02GvNERJaxgd/P0nDIWZWJc9YtL0SSB4bnF+cZNhr7MhPeI3qmboj9kEKxL5pPXJXvnREuUx3kFh87L7OCmClhMVbJ2IxdzM4GVFfMIv0DNZhqxzzMxpsbltjbZ1e2Kulez3JavsJ7P9Ey9yk1gp6pGY1j8H79J/y9Epec8ME0x+FpgC5D/api8S+BLJfb3HLnp2wojdJh3do0vyIXPDLHCNBMnE9YjwkG7DcB6jKZgtIGjK3E3KrLY97RdyNtCY+dwYvHhzcbT9E+fIq4aOkuygeqvFrGXFdHZa0GVUf3awiuovARZFyXvrCwjKSV63N98L8UvXvH+s=
  - secure: rpc109f1v9JVsoV15/1nUGG9K0NbhPdQVLxDt7RypH+yKmJzHOZf1rDNQOrRkCxU0T7/QFybZIeFBd0AGRDWLoOJ2BFpHZK+6hLwRwQzq0NWHyoWdLScp+xQfyRl0K5ybNxxXzkgB1g0LCc8160b/3AJGPzHNWUhfLzGiVOzg+QVKm/zArJ15fu1YPQSVQTsMxGyYe+HGONlq0Lzb6+C5159xg6sOH8SGl5Aa73H6JTPL3FX21pgogfgqIy2/9IGEe90vgxAxHGw66kHLw52Iddv2qE7uPjXi8yuIbRdlSpNb1AxJWE9z9c/yWfzXBipIgrFIRL9Wjge2OSHQvct0Cvn9a+fYWbYk+Mc/0UW24eMkU9gxEEA59MprrvgeaKkaNYWJDh82iwBtI3YRAft9S7T/x0eck5B635WjYera8QILjdS7LI5P4tw7R6eyIcIX7gQ7i95vxJpYVqWpgSs6yg7jrWjJzPkGYkzOZ3CT2w2y4D2AVeVTmMkxxxNHjFn0V0Fm8NAyAMmFEVUn/1Ntu1j0PP++EjRlwYLr/36mCnM4Y6ZCjDMJS/eX/5jwDfVFGbmK/hiAEFFUyPydZJFxLrXY6Z9YzqxCQY1Lg63+MOmcKQsQOQsxx8eFSBJKWE0cYPQswZP6Vl1OQoEZ5bmXBW0cTVI8/s0LSIznBjfjkw=

before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  
install:
  - java -version
  - ./mvnw -version
  - nvm ls-remote v8.11.3
  - nvm install v8.11.3 && node --version

before_script:
  - npm install -g vsce

script:
  - cd $TRAVIS_BUILD_DIR && ./mvnw clean install

after_success:
  - cd $TRAVIS_BUILD_DIR/jdl && ./gradlew clean installServer

before_deploy:
  - cd $TRAVIS_BUILD_DIR && chmod +x ./releng/scripts/build_products.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./releng/scripts/build_products.sh $TRAVIS_BUILD_DIR $TRAVIS_TAG $BT_USER $BT_APIKEY 1.7 1.7.0
    on:
       branch: master
